# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Pkg EdFi.Ods.Extensions.Sample

on:
  push:
    branches:  [main, 'b-v*-patch*','feature-*']

  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'distinct ID for Rebuild Database Templates workflow'
        required: false
        default: 'distinct_id'
          
permissions: read-all

env:
  INFORMATIONAL_VERSION: "7.3"
  BUILD_INCREMENTER: "9142"
  CONFIGURATION: "Release"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
  REF_NAME:  ${{ GITHUB.REF_NAME }}
  REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}

jobs:
  FindStandardAndExtensionVersions:
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-ODS/.github/workflows/Find Standard and Extension Versions.yml@874b608a0f3a14243e0035dd1222169fafcbe8d3
    with:
      calling_branch: ${{ github.head_ref || github.ref_name }}
      extension_path: 'Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample/EdFi.Ods.Extensions.Sample.csproj'

  build:
    if: ${{ always() }}
    needs: FindStandardAndExtensionVersions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
    name: build (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})        
    steps:
    - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
      run:  echo "${{ github.event.inputs.distinct_id }}" 
    - name: Check for Azure token
      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
      run: | 
        echo "::error::Missing Azure Token"
        exit 1  
    - name: Checkout Ed-Fi-Extensions
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Extensions
          path: Ed-Fi-Extensions/
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Checkout Ed-Fi-ODS
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/          
    - name: Is pull request branch exists in Ed-Fi-ODS-Implementation
      working-directory: ./Ed-Fi-Extensions/
      shell: pwsh
      run: |
        .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-ODS-Implementation"
    - name: Is pull request branch exists in Ed-Fi-ODS
      working-directory: ./Ed-Fi-Extensions/
      shell: pwsh
      run: |
        .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-ODS"
    - name: update BUILD_INCREMENTER 
      run: |      
            $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
            if ($newRevision -lt 0) {
                $newRevision = 1
                echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
            }
      shell: pwsh        
    - name: Cache Nuget packages       
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Run CodeGen
      run: |
          $ErrorActionPreference = 'Stop'
          . $env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/Initialize-PowershellForDevelopment.ps1
          Invoke-CodeGen -Engine PostgreSQL -ExtensionPaths  $env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample  -StandardVersion ${{ matrix.StandardVersion }}  -ExtensionVersion ${{ matrix.ExtensionVersion }}
      shell: pwsh
    - name: Restore
      working-directory: ./Ed-Fi-Extensions/
      run: |
        .\build.githubactions.ps1 restore -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample/EdFi.Ods.Extensions.Sample.csproj"
      shell: pwsh        
    - name: Build
      working-directory: ./Ed-Fi-Extensions/
      run: |
        .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample/EdFi.Ods.Extensions.Sample.csproj"  -StandardVersion ${{ matrix.StandardVersion }}
      shell: pwsh
    - name: Pack
      working-directory: ./Ed-Fi-Extensions/
      run: |
        .\build.githubactions.ps1 pack -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -PackageName "EdFi.Suite3.Ods.Extensions.Sample.${{ matrix.ExtensionVersion }}.Standard.${{ matrix.StandardVersion }}"  -ExtensionVersion ${{ matrix.ExtensionVersion }} -StandardVersion ${{ matrix.StandardVersion }}  -NuspecFilePath "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample/EdFi.Ods.Extensions.Sample.nuspec"
      shell: pwsh
    - name: Maximum Path Length Limitation Check
      working-directory: ./Ed-Fi-Extensions/
      run: |
        .\build.githubactions.ps1 MaximumPathLengthLimitation -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -PackageName "EdFi.Suite3.Ods.Extensions.Sample.${{ matrix.ExtensionVersion }}.Standard.${{ matrix.StandardVersion }}"
      shell: pwsh 
    - name: Install-credential-handler
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
      working-directory: ./Ed-Fi-Extensions/
      run: |
        .\build.githubactions.ps1 InstallCredentialHandler
      shell: pwsh        
    - name: publish
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
      working-directory: ./Ed-Fi-Extensions/
      shell: pwsh
      run: |
        .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.Sample/EdFi.Ods.Extensions.Sample.csproj" -PackageName "EdFi.Suite3.Ods.Extensions.Sample.${{ matrix.ExtensionVersion }}.Standard.${{ matrix.StandardVersion }}"
    - name: Upload EdFi.Ods.Extensions.Sample Artifact
      if: success()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
      with:
        name: EdFi.Ods.Extensions.Sample.Artifacts-${{ matrix.StandardVersion }}
        path: ${{ github.workspace }}/Ed-Fi-Extensions/NugetPackages/EdFi.Suite3.Ods.Extensions.Sample.*.*