name: EdFi.LoadTools Pull request build and test

on:
  pull_request:
    branches: [main]

env:
  INFORMATIONAL_VERSION: "5.4"
  CONFIGURATION: "Release"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: build
      run: |
        .\build.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -Solution "Utilities/DataLoading/LoadTools.sln"
      shell: pwsh
    - name: test
      run: |
        .\build.ps1 test -Configuration ${{ env.CONFIGURATION }} -Solution "Utilities/DataLoading/LoadTools.sln" -TestFilter "RunManually"
      shell: pwsh
