# When to Use :
   # 1.If any code change happens in EdFi.Installer.AppCommon Repository 
   # 2.If any code change happens in  \Ed-Fi-ODS-Implementation\InstallerPackages or \Ed-Fi-ODS-Implementation\logistics\scripts folder
   # 3.Before every actual nuget package release must run to get latest version updated in Azure Artifacts Feed
   # 4.At the time of  every major/minor version development must run to get new major/minor version updated in Azure Artifacts Feed

name: Instl EdFi.Installer.SwaggerUI Manually triggered build

on:
  workflow_dispatch:

permissions: read-all

env:
  INFORMATIONAL_VERSION: "7.3"
  BUILD_INCREMENTER: "9937"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Check for Azure token
      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
      run: | 
        echo "::error::Missing Azure Token"
        exit 1
    - name: Install-credential-handler
      run: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"
      shell: powershell
    - name: build
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
      run: |
        .\build-package.ps1 -InformationalVersion ${{env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -NugetFeed ${{env.AZURE_ARTIFACT_URL}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }}
      working-directory: InstallerPackages/EdFi.Installer.SwaggerUI
    - name: Upload EdFi.Installer.SwaggerUI Artifacts
      if: success()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
      with:
        name: NugetPackages.Artifacts
        path: ${{ github.workspace }}/InstallerPackages/EdFi.Installer.SwaggerUI/EdFi.Suite3.Installer.SwaggerUI.*.nupkg      

