name: Lib EdFi.Admin.DataAccess Pull request build and test

on:
  pull_request:
    branches: [main, 'ODS-*']

env:
  INFORMATIONAL_VERSION: "7.0"
  BUILD_INCREMENTER: "1"
  CONFIGURATION: "Release"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
    - name: Setup .NET
      uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
      with:
        dotnet-version: 6.0.x
    - name: Cache Nuget packages   
      uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 #v3.2.3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore NuGet packages
      run: |
        .\build.githubactions.ps1 restore -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln"
      shell: pwsh
    - name: build
      run: |
        .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj"
      shell: pwsh
    - name: Run Unit tests
      run: |
        .\build.githubactions.ps1 test -Configuration ${{ env.CONFIGURATION }} -Solution "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.sln" -ProjectFile "Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj"
      shell: pwsh
