name: Pull request build and test

on:
  pull_request:
    branches: [ main ]

env:
  INFORMATIONAL_VERSION: "5.4"
  CONFIGURATION: "Release"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/shared.yml
    with:
      publish: false
